[workspace]
resolver = "2"
members = [
    "crates/ployz-internal-secret",
    "crates/ployz-internal-cli-config",
    "crates/ployz-internal-gitutil",
    "crates/ployz-internal-machine-constants",
    "crates/ployz-internal-machine-network",
    "crates/ployz-internal-machine-osinfo",
    "crates/ployz-internal-metrics",
    "crates/ployz-scripts",
]

[workspace.package]
edition = "2024"
rust-version = "1.96"

[workspace.dependencies]
ployz-internal-secret = { path = "crates/ployz-internal-secret" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
