[workspace]
resolver = "2"
members = [
    "crates/ployz-internal-secret",
    "crates/ployz-internal-version",
    "crates/ployz-internal-grpcversion",
    "crates/ployz-internal-cli-config",
    "crates/ployz-internal-cli-progress",
    "crates/ployz-internal-cli-tui",
    "crates/ployz-internal-corrosion",
    "crates/ployz-internal-dns",
    "crates/ployz-internal-docker",
    "crates/ployz-internal-fs",
    "crates/ployz-internal-gitutil",
    "crates/ployz-internal-log",
    "crates/ployz-internal-machine-api-pb",
    "crates/ployz-internal-machine-api-proxy",
    "crates/ployz-internal-machine-constants",
    "crates/ployz-internal-machine-metrics",
    "crates/ployz-internal-machine-network",
    "crates/ployz-internal-machine-network-tunnel",
    "crates/ployz-internal-machine-osinfo",
    "crates/ployz-internal-metrics",
    "crates/ployz-internal-proxy",
    "crates/ployz-pkg-api",
    "crates/ployz-pkg-client-deploy-scheduler",
    "crates/ployz-scripts",
]

[workspace.package]
edition = "2024"
rust-version = "1.96"

[workspace.dependencies]
ployz-internal-secret = { path = "crates/ployz-internal-secret" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
