use std::cmp::Ordering;
use std::collections::BTreeMap;
use std::error::Error as StdError;
use std::fmt;
use std::future::Future;
use std::net::SocketAddr;
use std::pin::Pin;
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use ployz_internal_machine_store::ContainerRecord;
use ployz_pkg_api::{PORT_MODE_INGRESS, PROTOCOL_HTTP, PROTOCOL_HTTPS, ServiceContainer};

use crate::admin::CaddyAdminClient;
use crate::controller::{CADDY_SERVICE_NAME, VERIFY_PATH};
use crate::template::{TemplateContext, render_caddyfile};

const CADDYFILE_UNAVAILABLE_FOOTER: &str = "# NOTE: User-defined configs for services were skipped because Caddy is not running on this machine\n\
#       (not accessible via the shared admin socket /run/uncloud/caddy/admin.sock) or the latest\n\
#       generated config is invalid. Please check the service 'caddy' is running (uc inspect caddy)\n\
#       and its logs for more details (uc logs caddy).\n";

pub type ValidationError = Box<dyn StdError + Send + Sync>;
type ValidationFuture<'a> = Pin<Box<dyn Future<Output = Result<(), ValidationError>> + Send + 'a>>;

pub trait CaddyfileValidator: Send + Sync {
    fn validate<'a>(&'a self, caddyfile: &'a str) -> ValidationFuture<'a>;
}

impl CaddyfileValidator for CaddyAdminClient {
    fn validate<'a>(&'a self, caddyfile: &'a str) -> ValidationFuture<'a> {
        Box::pin(async move {
            CaddyAdminClient::validate(self, caddyfile)
                .await
                .map_err(|error| Box::new(error) as ValidationError)
        })
    }
}

#[derive(Debug)]
pub enum GenerateError {
    ValidatorUnavailable,
}

impl fmt::Display for GenerateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ValidatorUnavailable => formatter.write_str("Caddyfile validator is unavailable"),
        }
    }
}

impl StdError for GenerateError {}

pub struct CaddyfileGenerator {
    machine_id: String,
    machine_name: String,
    validator: Option<Arc<dyn CaddyfileValidator>>,
}

impl fmt::Debug for CaddyfileGenerator {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CaddyfileGenerator")
            .field("machine_id", &self.machine_id)
            .field("machine_name", &self.machine_name)
            .finish_non_exhaustive()
    }
}

impl CaddyfileGenerator {
    #[must_use]
    pub fn new(
        machine_id: impl Into<String>,
        machine_name: impl Into<String>,
        validator: Option<Arc<dyn CaddyfileValidator>>,
    ) -> Self {
        Self {
            machine_id: machine_id.into(),
            machine_name: machine_name.into(),
            validator,
        }
    }

    pub async fn generate(
        &self,
        records: &mut [ContainerRecord],
        include_custom: bool,
    ) -> Result<String, GenerateError> {
        records.sort_by(|left, right| self.compare_records(left, right));
        let containers = records
            .iter()
            .map(|record| record.container.clone())
            .collect::<Vec<_>>();
        let mut caddyfile = generate_base_from_ports(&containers, &self.machine_id);
        let header = format!(
            "# Caddyfile autogenerated by Uncloud on machine '{}' (DO NOT EDIT): {}\n\
# Automatically updated on service or health status changes.\n\
# Docs: https://uncloud.run/docs/concepts/ingress/overview\n",
            self.machine_name,
            rfc3339_utc(SystemTime::now())
        );
        if !include_custom {
            return Ok(format!(
                "{header}\n{caddyfile}\n{CADDYFILE_UNAVAILABLE_FOOTER}"
            ));
        }

        let upstreams = service_upstreams(&containers);
        let mut config_errors = Vec::new();
        let caddy_container = records
            .iter()
            .filter(|record| {
                record.machine_id == self.machine_id
                    && record.container.service_name() == CADDY_SERVICE_NAME
            })
            .reduce(|latest, candidate| {
                if created_time(candidate) > created_time(latest) {
                    candidate
                } else {
                    latest
                }
            })
            .map(|record| &record.container);

        if let Some(container) = caddy_container
            && !container.service_spec.caddy_config().is_empty()
        {
            let service_name = container.service_name();
            let context = TemplateContext {
                name: service_name.to_owned(),
                upstreams: upstreams.clone(),
            };
            match render_caddyfile_off_thread(
                context,
                container.service_spec.caddy_config().to_owned(),
            )
            .await
            {
                Err(error) => config_errors.push(format!(
                    "service '{service_name}': failed to render template: {error}"
                )),
                Ok(rendered) => {
                    let candidate = format!(
                        "# User-defined global config from service '{service_name}'.\n\
{rendered}\n\n{caddyfile}"
                    );
                    match self.validate(&candidate).await {
                        Ok(()) => caddyfile = candidate,
                        Err(error) => config_errors.push(format!(
                            "service '{service_name}': validation failed: {error}"
                        )),
                    }
                }
            }
        }

        let mut latest = BTreeMap::<String, &ServiceContainer>::new();
        for container in &containers {
            let service_name = container.service_name().to_owned();
            match latest.get(&service_name) {
                Some(previous)
                    if service_container_created_time(previous)
                        >= service_container_created_time(container) => {}
                _ => {
                    latest.insert(service_name, container);
                }
            }
        }

        for (service_name, container) in latest {
            if service_name == CADDY_SERVICE_NAME
                || container.service_spec.caddy_config().is_empty()
            {
                continue;
            }
            let context = TemplateContext {
                name: service_name.clone(),
                upstreams: upstreams.clone(),
            };
            let rendered = match render_caddyfile_off_thread(
                context,
                container.service_spec.caddy_config().to_owned(),
            )
            .await
            {
                Ok(rendered) => rendered,
                Err(error) => {
                    config_errors.push(format!(
                        "service '{service_name}': failed to render template: {error}"
                    ));
                    continue;
                }
            };
            let candidate = format!(
                "{caddyfile}\n# User-defined config for service '{service_name}'.\n{rendered}\n"
            );
            match self.validate(&candidate).await {
                Ok(()) => caddyfile = candidate,
                Err(error) => config_errors.push(format!(
                    "service '{service_name}': validation failed: {error}"
                )),
            }
        }

        if !config_errors.is_empty() {
            caddyfile.push_str("\n# Skipped invalid user-defined configs:\n");
            for error in config_errors {
                caddyfile.push_str("# - ");
                caddyfile.push_str(&error);
                caddyfile.push('\n');
            }
        }

        Ok(format!("{header}\n{caddyfile}"))
    }

    fn compare_records(&self, left: &ContainerRecord, right: &ContainerRecord) -> Ordering {
        let left_local = left.machine_id != self.machine_id;
        let right_local = right.machine_id != self.machine_id;
        left_local
            .cmp(&right_local)
            .then_with(|| {
                left.container
                    .service_name()
                    .cmp(right.container.service_name())
            })
            .then_with(|| created_time(left).cmp(&created_time(right)))
    }

    async fn validate(&self, caddyfile: &str) -> Result<(), ValidationError> {
        let validator = self
            .validator
            .as_ref()
            .ok_or_else(|| Box::new(GenerateError::ValidatorUnavailable) as ValidationError)?;
        validator.validate(caddyfile).await
    }
}

async fn render_caddyfile_off_thread(
    context: TemplateContext,
    source: String,
) -> Result<String, String> {
    tokio::task::spawn_blocking(move || render_caddyfile(&context, &source))
        .await
        .map_err(|error| format!("template worker failed: {error}"))?
}

fn created_time(record: &ContainerRecord) -> Option<ployz_pkg_api::Rfc3339Time> {
    service_container_created_time(&record.container)
}

fn service_container_created_time(
    container: &ServiceContainer,
) -> Option<ployz_pkg_api::Rfc3339Time> {
    let mut container = container.container.clone();
    container.created_time()
}

pub(super) fn generate_base_from_ports(
    containers: &[ServiceContainer],
    verify_response: &str,
) -> String {
    let (http, https) = http_upstreams_from_ports(containers);
    let mut output = format!(
        "# Health check endpoint to verify Caddy reachability on this machine.\n\
http:// {{\n\
\thandle {VERIFY_PATH} {{\n\
\t\trespond \"{verify_response}\" 200\n\
\t}}\n\
\tlog\n\
}}\n\n\
(common_proxy) {{\n\
\t# Retry failed requests up to lb_retries times against other available upstreams.\n\
\tlb_retries 3\n\
\t# Upstreams are marked unhealthy for fail_duration after a failed request (passive health checking).\n\
\tfail_duration 30s\n\
}}\n"
    );
    if !http.is_empty() || !https.is_empty() {
        output.push_str("\n# Sites generated from service ports.\n");
    }
    append_sites(&mut output, "http", &http);
    append_sites(&mut output, "https", &https);
    output
}

fn append_sites(output: &mut String, scheme: &str, sites: &BTreeMap<String, Vec<String>>) {
    for (hostname, upstreams) in sites {
        output.push_str(&format!(
            "\n{scheme}://{hostname} {{\n\
\treverse_proxy {} {{\n\
\t\timport common_proxy\n\
\t}}\n\
\tlog\n\
}}\n",
            upstreams.join(" ")
        ));
    }
}

pub(super) fn http_upstreams_from_ports(
    containers: &[ServiceContainer],
) -> (BTreeMap<String, Vec<String>>, BTreeMap<String, Vec<String>>) {
    let mut http = BTreeMap::<String, Vec<String>>::new();
    let mut https = BTreeMap::<String, Vec<String>>::new();
    for container in containers {
        let Some(ip) = container.container.uncloud_network_ip() else {
            continue;
        };
        let ports = match container.service_ports() {
            Ok(ports) => ports,
            Err(error) => {
                eprintln!(
                    "Failed to parse service ports for container: container={} error={error}",
                    container.container.id
                );
                continue;
            }
        };
        for port in ports {
            if port.mode != PORT_MODE_INGRESS {
                continue;
            }
            let upstream = SocketAddr::new(ip, port.container_port).to_string();
            match port.protocol.as_str() {
                PROTOCOL_HTTP => http.entry(port.hostname).or_default().push(upstream),
                PROTOCOL_HTTPS => https.entry(port.hostname).or_default().push(upstream),
                _ => {
                    eprintln!(
                        "Unsupported protocol for ingress port: container={} port={port:?}",
                        container.container.id
                    );
                }
            }
        }
    }
    (http, https)
}

fn service_upstreams(containers: &[ServiceContainer]) -> BTreeMap<String, Vec<String>> {
    let mut upstreams = BTreeMap::<String, Vec<String>>::new();
    for container in containers {
        let Some(ip) = container.container.uncloud_network_ip() else {
            continue;
        };
        upstreams
            .entry(container.service_name().to_owned())
            .or_default()
            .push(ip.to_string());
    }
    upstreams
}

fn rfc3339_utc(time: SystemTime) -> String {
    let seconds = match time.duration_since(UNIX_EPOCH) {
        Ok(duration) => duration.as_secs() as i64,
        Err(error) => {
            let duration = error.duration();
            -(duration.as_secs() as i64) - i64::from(duration.subsec_nanos() != 0)
        }
    };
    let days = seconds.div_euclid(86_400);
    let seconds_of_day = seconds.rem_euclid(86_400);
    let (year, month, day) = civil_from_days(days);
    let hour = seconds_of_day / 3600;
    let minute = seconds_of_day % 3600 / 60;
    let second = seconds_of_day % 60;
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z")
}

fn civil_from_days(days: i64) -> (i64, i64, i64) {
    let days = days + 719_468;
    let era = if days >= 0 { days } else { days - 146_096 } / 146_097;
    let day_of_era = days - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let mut year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_prime + 2) / 5 + 1;
    let month = month_prime + if month_prime < 10 { 3 } else { -9 };
    year += i64::from(month <= 2);
    (year, month, day)
}

#[cfg(test)]
mod tests {
    use std::future::Future;
    use std::net::IpAddr;
    use std::pin::Pin;
    use std::sync::Arc;

    use ployz_internal_machine_store::StoreTimestamp;
    use ployz_pkg_api::ServiceContainer;
    use serde_json::json;

    use super::*;

    fn container(ip: Option<&str>, service: &str, ports: &[&str]) -> ServiceContainer {
        configured_container(ip, service, ports, "", "2026-08-12T00:00:00Z")
    }

    fn configured_container(
        ip: Option<&str>,
        service: &str,
        ports: &[&str],
        caddy_config: &str,
        created: &str,
    ) -> ServiceContainer {
        let value = json!({
            "Id": format!("{service}-{}", ip.unwrap_or_default()),
            "Created": created,
            "State": {"Running": true},
            "Config": {"Labels": {
                "uncloud.service.name": service,
                "uncloud.service.ports": ports.join(",")
            }},
            "NetworkSettings": {"Networks": {
                "uncloud": {"IPAddress": ip.unwrap_or_default()}
            }},
            "ServiceSpec": if caddy_config.is_empty() {
                json!({})
            } else {
                json!({"Caddy": {"Config": caddy_config}})
            }
        });
        ServiceContainer::from_json(&serde_json::to_vec(&value).unwrap()).unwrap()
    }

    fn record(container: ServiceContainer, machine_id: &str) -> ContainerRecord {
        ContainerRecord {
            container,
            machine_id: machine_id.into(),
            sync_status: String::new(),
            updated_at: StoreTimestamp::parse("2026-08-12 00:00:00").unwrap(),
        }
    }

    struct TestValidator;

    impl CaddyfileValidator for TestValidator {
        fn validate<'a>(
            &'a self,
            caddyfile: &'a str,
        ) -> Pin<Box<dyn Future<Output = Result<(), ValidationError>> + Send + 'a>> {
            Box::pin(async move {
                if caddyfile.contains("# test:invalid") {
                    Err(Box::new(std::io::Error::other("invalid config detected"))
                        as ValidationError)
                } else {
                    Ok(())
                }
            })
        }
    }

    fn generated_body(generated: &str) -> &str {
        generated.split_once('\n').unwrap().1
    }

    #[test]
    fn base_generator_matches_oracle_ordering_and_format() {
        let containers = vec![
            container(
                Some("10.210.0.3"),
                "api",
                &["app.example.com:8080/http", "secure.example.com:8443/https"],
            ),
            container(Some("10.210.0.2"), "api", &["app.example.com:8080/http"]),
        ];
        let generated = generate_base_from_ports(&containers, "machine-id");
        assert!(
            generated.contains(
                "http://app.example.com {\n\treverse_proxy 10.210.0.3:8080 10.210.0.2:8080"
            )
        );
        assert!(
            generated.contains("https://secure.example.com {\n\treverse_proxy 10.210.0.3:8443")
        );
        assert!(generated.starts_with("# Health check endpoint"));
        assert!(generated.ends_with("}\n"));
    }

    #[test]
    fn utc_timestamp_matches_go_second_precision_shape() {
        assert_eq!(rfc3339_utc(UNIX_EPOCH), "1970-01-01T00:00:00Z");
        assert_eq!(
            rfc3339_utc(UNIX_EPOCH + std::time::Duration::from_nanos(1)),
            "1970-01-01T00:00:00Z"
        );
    }

    #[tokio::test(flavor = "current_thread")]
    async fn equal_created_global_configs_keep_first_stable_record() {
        let mut records = vec![
            record(
                configured_container(
                    Some("10.210.0.2"),
                    CADDY_SERVICE_NAME,
                    &[],
                    "first-global",
                    "2026-08-12T00:00:00Z",
                ),
                "test-machine-id",
            ),
            record(
                configured_container(
                    Some("10.210.0.3"),
                    CADDY_SERVICE_NAME,
                    &[],
                    "second-global",
                    "2026-08-12T00:00:00Z",
                ),
                "test-machine-id",
            ),
        ];
        let generator = CaddyfileGenerator::new(
            "test-machine-id",
            "test-machine",
            Some(Arc::new(TestValidator)),
        );
        let generated = generator.generate(&mut records, true).await.unwrap();
        assert!(generated.contains("first-global"));
        assert!(!generated.contains("second-global"));
    }

    #[test]
    fn socket_address_format_brackets_ipv6() {
        assert_eq!(
            SocketAddr::new("2001:db8::1".parse::<IpAddr>().unwrap(), 8080).to_string(),
            "[2001:db8::1]:8080"
        );
    }

    #[tokio::test(flavor = "current_thread")]
    async fn complete_generated_body_matches_oracle() {
        let mut records = vec![
            record(
                container(Some("10.210.0.2"), "app", &["app.example.com:8080/http"]),
                "remote",
            ),
            record(
                container(Some("10.210.1.2"), "app", &["app.example.com:8080/http"]),
                "test-machine-id",
            ),
        ];
        let generated = CaddyfileGenerator::new("test-machine-id", "test-machine", None)
            .generate(&mut records, true)
            .await
            .unwrap();
        assert_eq!(
            generated_body(&generated),
            "# Automatically updated on service or health status changes.\n\
# Docs: https://uncloud.run/docs/concepts/ingress/overview\n\n\
# Health check endpoint to verify Caddy reachability on this machine.\n\
http:// {\n\
\thandle /.uncloud-verify {\n\
\t\trespond \"test-machine-id\" 200\n\
\t}\n\
\tlog\n\
}\n\n\
(common_proxy) {\n\
\t# Retry failed requests up to lb_retries times against other available upstreams.\n\
\tlb_retries 3\n\
\t# Upstreams are marked unhealthy for fail_duration after a failed request (passive health checking).\n\
\tfail_duration 30s\n\
}\n\n\
# Sites generated from service ports.\n\n\
http://app.example.com {\n\
\treverse_proxy 10.210.1.2:8080 10.210.0.2:8080 {\n\
\t\timport common_proxy\n\
\t}\n\
\tlog\n\
}\n"
        );
    }

    #[tokio::test(flavor = "current_thread")]
    async fn custom_configs_use_latest_sorted_service_and_report_failures() {
        let mut records = vec![
            record(
                configured_container(
                    Some("10.210.0.2"),
                    "web",
                    &[],
                    "old.example { respond old }",
                    "2026-08-12T00:00:00Z",
                ),
                "remote",
            ),
            record(
                configured_container(
                    Some("10.210.0.3"),
                    "web",
                    &[],
                    "web.example { reverse_proxy {{upstreams 8080}} }",
                    "2026-08-12T01:00:00Z",
                ),
                "remote",
            ),
            record(
                configured_container(
                    Some("10.210.0.4"),
                    "broken",
                    &[],
                    "# test:invalid\nbroken.example { respond broken }",
                    "2026-08-12T00:00:00Z",
                ),
                "remote",
            ),
        ];
        let generator = CaddyfileGenerator::new(
            "test-machine-id",
            "test-machine",
            Some(Arc::new(TestValidator)),
        );
        let generated = generator.generate(&mut records, true).await.unwrap();
        assert!(generated.contains(
            "# User-defined config for service 'web'.\nweb.example { reverse_proxy 10.210.0.2:8080 10.210.0.3:8080 }\n"
        ));
        assert!(!generated.contains("old.example"));
        assert!(generated.ends_with(
            "# Skipped invalid user-defined configs:\n# - service 'broken': validation failed: invalid config detected\n"
        ));
    }

    #[tokio::test(flavor = "current_thread")]
    async fn unavailable_mode_skips_custom_and_appends_exact_footer() {
        let mut records = vec![record(
            configured_container(
                Some("10.210.0.2"),
                "web",
                &[],
                "web.example { respond custom }",
                "2026-08-12T00:00:00Z",
            ),
            "test-machine-id",
        )];
        let generated = CaddyfileGenerator::new("test-machine-id", "test-machine", None)
            .generate(&mut records, false)
            .await
            .unwrap();
        assert!(!generated.contains("respond custom"));
        assert!(generated.ends_with(CADDYFILE_UNAVAILABLE_FOOTER));
    }
}
