[package]
name = "ployz-internal-machine-corroservice"
version = "0.0.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
backon = { version = "=1.6.0", default-features = false, features = ["std", "tokio-sleep"] }
bollard = { version = "=0.21.0", default-features = false, features = ["pipe", "ssl"] }
fastrand = { version = "=2.5.0", default-features = false, features = ["std"] }
futures-util = { version = "=0.3.34", default-features = false, features = ["std"] }
ployz-internal-corrosion = { path = "../ployz-internal-corrosion" }
ployz-internal-fs = { path = "../ployz-internal-fs" }
ployz-pkg-api = { path = "../ployz-pkg-api" }
serde = { version = "=1.0.229", default-features = false, features = ["derive", "std"] }
tokio = { version = "=1.53.1", default-features = false, features = ["macros", "rt", "sync", "time"] }
toml = { version = "=1.1.4+spec-1.1.0", default-features = false, features = ["display", "parse", "serde", "std"] }
tracing = { version = "=0.1.44", default-features = false, features = ["std"] }

[target.'cfg(target_os = "linux")'.dependencies]
libsystemd = "=0.7.2"
