[package]
name = "ployz-internal-machine-metrics"
version = "0.0.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
flate2 = { version = "=1.1.9", default-features = false, features = ["rust_backend"] }
http-body-util = { version = "=0.1.4", default-features = false }
hyper = { version = "=1.11.0", default-features = false, features = ["http1", "server"] }
hyper-util = { version = "=0.1.20", default-features = false, features = ["tokio"] }
ployz-internal-metrics = { path = "../ployz-internal-metrics" }
prometheus = { version = "=0.14.0", default-features = false, features = ["protobuf"] }
protobuf = { version = "=3.7.2", default-features = false }
tokio = { version = "=1.53.1", default-features = false, features = ["io-util", "macros", "net", "rt", "sync", "time"] }
tokio-util = { version = "=0.7.19", default-features = false }
