//! Typed protobuf and gRPC API shared by Ployz machine components.
//!
//! The generated snapshot is checked in so ordinary and cross-target builds do
//! not execute a host `protoc`. Set `PLOYZ_PROTO_VERIFY=1` to regenerate into
//! Cargo's output directory and compare every generated byte, or
//! `PLOYZ_PROTO_REGENERATE=1` to deliberately refresh the checked snapshot.
//! `tests/acceptance.sh` is the repository-owned regeneration and bidirectional
//! Go/Rust differential gate.
//! Prost intentionally drops unknown fields on typed decode/re-encode; proxy
//! paths that must retain them operate on raw protobuf envelopes instead.

mod generated {
    pub mod google {
        pub mod rpc {
            include!("generated/google.rpc.rs");
        }
    }

    pub mod api {
        include!("generated/api.rs");
    }
}

pub use generated::api::*;
pub use generated::google;

use std::fmt;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr};

use tonic::{Code, Status};

/// WireGuard public and private keys are exactly 32 bytes.
pub const KEY_LEN: usize = 32;

/// A Go `netip.Addr` value, including its arbitrary IPv6 zone bytes.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct Address {
    ip: IpAddr,
    zone: Vec<u8>,
}

impl Address {
    #[must_use]
    pub fn scoped(ip: Ipv6Addr, zone: impl Into<Vec<u8>>) -> Self {
        Self {
            ip: IpAddr::V6(ip),
            zone: zone.into(),
        }
    }

    #[must_use]
    pub fn ip(&self) -> IpAddr {
        self.ip
    }

    #[must_use]
    pub fn zone(&self) -> &[u8] {
        &self.zone
    }

    pub fn to_std(&self) -> Result<IpAddr, AddressError> {
        if self.zone.is_empty() {
            Ok(self.ip)
        } else {
            Err(AddressError::ScopedIp)
        }
    }
}

impl From<IpAddr> for Address {
    fn from(ip: IpAddr) -> Self {
        Self {
            ip,
            zone: Vec::new(),
        }
    }
}

/// A Go `netip.AddrPort`, retaining an IPv6 zone when present.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct AddrPort {
    address: Address,
    port: u16,
}

impl AddrPort {
    #[must_use]
    pub fn new(address: Address, port: u16) -> Self {
        Self { address, port }
    }

    #[must_use]
    pub fn address(&self) -> &Address {
        &self.address
    }

    #[must_use]
    pub fn port(&self) -> u16 {
        self.port
    }

    pub fn to_std(&self) -> Result<SocketAddr, AddressError> {
        Ok(SocketAddr::new(self.address.to_std()?, self.port))
    }
}

impl From<SocketAddr> for AddrPort {
    fn from(address: SocketAddr) -> Self {
        Self {
            address: address.ip().into(),
            port: address.port(),
        }
    }
}

/// An invalid binary IP, socket address, or prefix.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum AddressError {
    InvalidIp,
    UnexpectedSliceSize,
    InvalidPrefix,
    ScopedIp,
}

impl fmt::Display for AddressError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidIp => formatter.write_str("invalid IP"),
            Self::UnexpectedSliceSize => formatter.write_str("unmarshal IP: unexpected slice size"),
            Self::InvalidPrefix => formatter.write_str("invalid prefix"),
            Self::ScopedIp => formatter.write_str("scoped IP has no std::net representation"),
        }
    }
}

impl std::error::Error for AddressError {}

impl Ip {
    #[must_use]
    pub fn new(address: impl Into<Address>) -> Self {
        let address = address.into();
        let mut ip = match address.ip {
            IpAddr::V4(address) => address.octets().to_vec(),
            IpAddr::V6(address) => address.octets().to_vec(),
        };
        ip.extend_from_slice(&address.zone);
        Self { ip }
    }

    pub fn to_addr(&self) -> Result<Address, AddressError> {
        match self.ip.as_slice() {
            [] => Err(AddressError::InvalidIp),
            [a, b, c, d] => Ok(IpAddr::V4(Ipv4Addr::new(*a, *b, *c, *d)).into()),
            bytes if bytes.len() == 16 => {
                let octets: [u8; 16] = bytes.try_into().expect("length was checked");
                Ok(IpAddr::V6(Ipv6Addr::from(octets)).into())
            }
            bytes if bytes.len() > 16 => {
                let octets: [u8; 16] = bytes[..16].try_into().expect("length was checked");
                Ok(Address {
                    ip: Ipv6Addr::from(octets).into(),
                    zone: bytes[16..].to_vec(),
                })
            }
            _ => Err(AddressError::UnexpectedSliceSize),
        }
    }
}

impl From<IpAddr> for Ip {
    fn from(address: IpAddr) -> Self {
        Self::new(address)
    }
}

impl IpPort {
    #[must_use]
    pub fn new(address: impl Into<AddrPort>) -> Self {
        let address = address.into();
        Self {
            ip: Some(Ip::new(address.address)),
            port: u32::from(address.port),
        }
    }

    pub fn to_addr_port(&self) -> Result<AddrPort, AddressError> {
        // The frozen helper dereferences a nil nested IP and panics. Retain that
        // malformed-message limitation instead of silently normalizing it.
        let address = self.ip.as_ref().expect("IP not set").to_addr()?;
        // The frozen helper narrows uint32 to uint16 without rejecting overflow.
        #[allow(clippy::cast_possible_truncation)]
        let port = self.port as u16;
        Ok(AddrPort { address, port })
    }

    pub fn to_socket_addr(&self) -> Result<SocketAddr, AddressError> {
        self.to_addr_port()?.to_std()
    }
}

impl From<SocketAddr> for IpPort {
    fn from(address: SocketAddr) -> Self {
        Self::new(address)
    }
}

impl IpPrefix {
    #[must_use]
    pub fn new(address: IpAddr, bits: u8) -> Self {
        Self {
            ip: Some(Ip::new(address)),
            bits: u32::from(bits),
        }
    }

    pub fn to_prefix(&self) -> Result<(IpAddr, u8), AddressError> {
        // As in the frozen helper, an absent nested IP is a panic rather than a
        // validation error.
        let address = self.ip.as_ref().expect("IP not set").to_addr()?;
        let address = address.to_std().map_err(|_| AddressError::InvalidPrefix)?;
        let maximum = if address.is_ipv4() { 32 } else { 128 };
        if self.bits > maximum {
            return Err(AddressError::InvalidPrefix);
        }
        Ok((address, self.bits as u8))
    }
}

impl NetworkConfig {
    /// Applies the frozen cluster network validation contract.
    pub fn validate(&self) -> Result<(), Status> {
        if let Some(subnet) = &self.subnet {
            subnet
                .to_prefix()
                .map_err(|error| invalid_argument(format!("invalid subnet: {error}")))?;
        }
        if let Some(management_ip) = &self.management_ip {
            management_ip
                .to_addr()
                .map_err(|error| invalid_argument(format!("invalid management IP: {error}")))?;
        }
        for endpoint in &self.endpoints {
            endpoint
                .to_addr_port()
                .map_err(|error| invalid_argument(format!("invalid endpoint: {error}")))?;
        }
        // Proto3 bytes do not retain Go's nil-versus-empty in-memory distinction.
        // Both decode as empty; report the observable wire-level missing case.
        if self.public_key.is_empty() {
            return Err(invalid_argument("public key not set"));
        }
        if self.public_key.len() != KEY_LEN {
            return Err(invalid_argument(format!(
                "invalid public key length: {}",
                self.public_key.len()
            )));
        }
        Ok(())
    }
}

fn invalid_argument(message: impl Into<String>) -> Status {
    Status::new(Code::InvalidArgument, message.into())
}

/// Frozen descriptors for all five API schemas and `google.rpc.Status`.
pub const FILE_DESCRIPTOR_SET: &[u8] = include_bytes!("../schema/ployz-api.pb");
