[package]
name = "ployz-internal-cli-logs"
version = "0.0.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
clap = { version = "=4.6.6", default-features = false, features = ["derive", "std", "help", "usage", "error-context"] }
jiff = { version = "=0.2.35", default-features = false, features = ["tz-system", "tzdb-zoneinfo"] }
ployz-internal-cli-tui = { path = "../ployz-internal-cli-tui" }
ployz-pkg-api = { path = "../ployz-pkg-api" }
